# Spring application configuration
spring:

  application:
    name: srw-springboot  # Name of the application

  server:
    port: ${PORT:8080}  # Dynamic port provided by Railway
    session:
      timeout: 1440m  # Set session timeout to 24 hours

  jpa:
    hibernate:
      ddl-auto: update  # Auto-update schema
    show-sql: false  # Disables logging of SQL queries
    open-in-view: false  # Disable open-in-view to prevent lazy loading during view rendering

  cache:
    type: redis  # Redis as the cache provider

  # Separate JPA and Redis repository configurations
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: false  # Disable Redis repositories since JPA entities are used

---
# Development profile configuration
spring:
  config:
    activate:
      on-profile: dev  # Set profile to 'dev' for development environment

  datasource:
    url: ${DEV_DB_URL}  # Dynamic database URL for development
    username: ${DEV_DB_USERNAME}  # Dynamic database username for development
    password: ${DEV_DB_PASSWORD}  # Dynamic database password for development
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver

  redis:
    host: ${DEV_REDIS_HOST}  # Redis host for dev environment
    port: ${DEV_REDIS_PORT}  # Redis port for dev environment
  cache:
    redis:
      time-to-live: 900000  # TTL in milliseconds

jwt:
  secret: ${DEV_JWT_SECRET}
  expiration: ${DEV_JWT_EXPIRATION}

frontend:
  base-url: ${DEV_FRONTEND_BASE_URL}

# Suppress Spring Security configuration warning
logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR